/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import dirt from './dirt.glb'

type GLTFResult = GLTF & {
  nodes: {
    dirt: THREE.Mesh
  }
  materials: {
    dirt: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(dirt) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.dirt.geometry} material={materials.dirt} />
    </group>
  )
}

useGLTF.preload(dirt)
