/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    unit_boat: THREE.Mesh
    Group: THREE.Mesh
    Group_1: THREE.Mesh
    Group_2: THREE.Mesh
    Group_3: THREE.Mesh
    Group_4: THREE.Mesh
    Group_5: THREE.Mesh
  }
  materials: {
    dirt: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('./unit_boat.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.unit_boat.geometry} material={nodes.unit_boat.material}>
        <mesh
          geometry={nodes.Group.geometry}
          material={nodes.Group.material}
          position={[-0.13, 0.12, -0.09]}
          rotation={[-Math.PI / 4, 0, -Math.PI / 2]}
          scale={[0.21, 0.43, 0.29]}
        />
        <mesh
          geometry={nodes.Group_1.geometry}
          material={nodes.Group_1.material}
          position={[0.11, 0.12, -0.09]}
          rotation={[-Math.PI / 4, 0, -Math.PI / 2]}
          scale={[0.21, 0.43, 0.29]}
        />
        <mesh
          geometry={nodes.Group_2.geometry}
          material={nodes.Group_2.material}
          position={[-0.02, 0.12, 0.09]}
          rotation={[-2.36, 0, -Math.PI / 2]}
          scale={[-0.21, 0.43, 0.29]}
        />
        <mesh
          geometry={nodes.Group_3.geometry}
          material={nodes.Group_3.material}
          position={[-0.13, 0.12, 0.09]}
          rotation={[-2.36, 0, -Math.PI / 2]}
          scale={[-0.21, 0.43, 0.29]}
        />
        <mesh
          geometry={nodes.Group_4.geometry}
          material={nodes.Group_4.material}
          position={[0.11, 0.12, 0.09]}
          rotation={[-2.36, 0, -Math.PI / 2]}
          scale={[-0.21, 0.43, 0.29]}
        />
        <mesh
          geometry={nodes.Group_5.geometry}
          material={nodes.Group_5.material}
          position={[-0.02, 0.12, -0.09]}
          rotation={[-Math.PI / 4, 0, -Math.PI / 2]}
          scale={[0.21, 0.43, 0.29]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('./unit_boat.glb')
